# Generated by Django 3.2.12 on 2023-01-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
