# Generated by Django 3.2.12 on 2023-01-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_customuser_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(max_length=100),
        ),
    ]
